{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX001.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX002.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX003.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX004.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX005.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX006.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX007.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX008.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX009.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX010.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX011.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX012.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX013.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX014.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX015.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX016.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX017.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX018.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX019.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX020.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX021.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX022.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX023.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX024.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX025.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX026.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX027.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX028.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX029.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX030.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX031.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX032.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX033.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX034.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX035.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX036.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX037.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX038.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX039.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX040.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX041.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX042.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX043.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX044.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX045.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX046.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX047.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX048.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX049.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX050.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX051.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX052.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX053.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX054.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX055.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX056.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX057.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX058.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX059.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX060.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX061.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX062.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX063.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX064.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX065.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX066.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX067.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX068.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX069.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX070.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX071.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX072.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX073.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX074.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX075.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX076.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX077.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX078.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX079.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX080.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX081.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX082.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX083.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX084.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX085.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX086.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX087.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX088.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX089.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX090.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX091.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX092.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX093.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX094.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX095.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX096.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX097.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX098.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX099.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX100.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX101.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX102.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX103.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX104.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX105.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX106.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX107.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX108.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX109.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX110.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX111.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX112.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX113.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX114.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX115.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX116.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX117.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX118.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX119.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX120.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX121.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX122.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX123.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX124.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX125.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX126.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX127.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX128.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX129.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX130.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX131.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX132.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX133.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX134.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX135.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX136.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX137.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX138.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX139.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX140.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX141.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX142.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX143.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX144.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX145.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX146.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX147.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX148.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX149.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX150.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX151.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX152.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX153.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX154.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX155.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX156.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX157.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX158.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX159.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX160.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX161.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX162.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX163.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX164.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX165.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX166.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX167.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX168.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX169.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX170.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX171.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX172.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX173.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX174.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX175.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX176.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX177.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX178.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX179.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX180.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX181.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX182.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX183.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX184.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX185.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX186.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX187.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX188.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX189.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX190.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX191.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX192.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX193.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX194.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX195.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX196.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX197.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX198.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX199.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX200.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX201.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX202.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX203.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX204.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX205.wav", "duration": 10.0, "text": ""}
{"audio_filepath": "/mnt/rds/redhen/gallina/Singularity/Zhaoqing/example/split/EX206.wav", "duration": 4.594467120181406, "text": ""}
